#!/usr/bin/env python3
"""AGENTS.md v7.0 재작성 스크립트."""
from __future__ import annotations
import io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
from pathlib import Path

ROOT = Path(__file__).parent.parent
AGENTS_MD = ROOT / "AGENTS.md"

CONTENT = (
    "# Loomix Agent Teams v7.0 운영 가이드\n"
    "\n"
    "> **브랜드**: Loomix (AI 콘텐츠 에이전시) · **내부 코드명**: KAS\n"
    "> **버전**: v7.0 | **에이전트 수**: 23개 | **기준일**: 2026-04-13\n"
    "> **공식 Claude Code 문서 준수**: 100% (color enum, frontmatter, hook 구조)\n"
    "\n"
    "---\n"
    "\n"
    "## 조직도 — 9 부서 × 23명\n"
    "\n"
    "```\n"
    "                             ceo (Sonnet) — Executive 부서장\n"
    "                                 |\n"
    "   +------+--------+---------+--+----+--------+--------+--------+--------+\n"
    "   v      v        v         v       v        v        v        v        v\n"
    "Exec   Eng      Ops      QA   Creat   Sales  Growth   Fin     Data\n"
    "(3명)  (4명)    (4명)    (3명) (2명)   (2명)  (2명)    (1명)   (2명)\n"
    "\n"
    "ceo    db-arch  devops   qa-aud  content  sales   marketing  finance  data-anal\n"
    "cto    backend  code-ref perf-a  revenue  project customer            prompt-e\n"
    "legal  frontend pipeline ux-aud\n"
    "       ui-des   release\n"
    "```\n"
    "\n"
    "**모델 분포**: Opus 2 (cto, db-architect) · Sonnet 14 · Haiku 7\n"
    "**부서장 9명**: ceo · db-architect · devops-engineer · qa-auditor · "
    "content-director · sales-manager · marketing-manager · finance-manager · data-analyst\n"
    "\n"
    "---\n"
    "\n"
    "## 부서별 정의\n"
    "\n"
    "### Executive Office — 3명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **ceo** | Sonnet | **부서장** · HITL 판단 · 비즈니스 미션팀 결성 · 월간 경영 보고 |\n"
    "| **cto** | Opus | 기술 조율 · 기술 미션팀 결성 · HITL 감지 · 코드 직접 수정 금지 |\n"
    "| **legal-counsel** | Haiku | 계약서·NDA·저작권·YouTube 정책 검토 (read-only) |\n"
    "\n"
    "### Engineering Division — 4명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **db-architect** | Opus | **부서장** · DB 스키마 · RLS 정책 · types.ts 동기화 |\n"
    "| **backend-engineer** | Sonnet | src/ 전체 · 파이프라인 · 테스트 · scripts/ |\n"
    "| **frontend-engineer** | Sonnet | web/ 전체 · Next.js · E2E 테스트 |\n"
    "| **ui-designer** | Sonnet | globals.css · 디자인 시스템 · 썸네일 에셋 |\n"
    "\n"
    "### Platform Operations — 4명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **devops-engineer** | Sonnet | **부서장** · 인프라 · 문서 · hooks · 비용 모니터링 |\n"
    "| **code-refactorer** | Sonnet | God Module 분해 · 의존성 정리 (worktree) |\n"
    "| **pipeline-debugger** | Sonnet | Step 실패 분석 · 로그·manifest·쿼터 (read-only) |\n"
    "| **release-manager** | Haiku | CHANGELOG · git tag · PR 관리 |\n"
    "\n"
    "### Quality Assurance — 3명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **qa-auditor** | Sonnet | **부서장** · OWASP 감사 · 주간 감사팀 결성 (TeamCreate) |\n"
    "| **performance-analyst** | Haiku | N+1·메모리·번들·폴링 분석 (read-only) |\n"
    "| **ux-auditor** | Haiku | WCAG 2.1 AA · UX · 반응형 감사 (read-only) |\n"
    "\n"
    "### Creative Studio — 2명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **content-director** | Sonnet | **부서장** · 스크립트·썸네일·SEO·채널 품질 감사 (read-only) |\n"
    "| **revenue-strategist** | Sonnet | 수익 주제 선별 · scorer · 포트폴리오 전략 (read-only) |\n"
    "\n"
    "### Sales & Delivery — 2명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **sales-manager** | Sonnet | **부서장** · 리드 발굴 · 제안서 · 계약 (법적문서→legal-counsel 경유) |\n"
    "| **project-manager** | Sonnet | 수주 프로젝트 딜리버리 관리 |\n"
    "\n"
    "### Growth & Brand — 2명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **marketing-manager** | Sonnet | **부서장** · 브랜드 성장 · 인바운드 마케팅 |\n"
    "| **customer-support** | Haiku | 고객 문의 · 수정 요청 · FAQ |\n"
    "\n"
    "### Finance Operations — 1명\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **finance-manager** | Haiku | **부서장** · 청구서 · P&L · API 비용 추적 |\n"
    "\n"
    "### Data Intelligence — 2명 (v7.0 신규)\n"
    "| 에이전트 | 모델 | 역할 |\n"
    "|---|:-:|---|\n"
    "| **data-analyst** | Haiku | **부서장** · Supabase BI · 채널 코호트 · 월간 대시보드 |\n"
    "| **prompt-engineer** | Sonnet | Gemini/ElevenLabs 프롬프트 버전 관리 · A/B · 토큰 절감 |\n"
    "\n"
    "---\n"
    "\n"
    "## 파일 소유권\n"
    "\n"
    "| 에이전트 | 소유 경로 | 금지 경로 |\n"
    "|----------|----------|----------|\n"
    "| backend-engineer | src/, tests/, scripts/ (migrations 제외) | web/ |\n"
    "| frontend-engineer | web/app/, web/lib/, web/hooks/, web/components/(로직) | src/, globals.css |\n"
    "| ui-designer | web/app/globals.css, web/public/, assets/thumbnails/, web/components/(스타일) | src/, tests/ |\n"
    "| devops-engineer | .claude/, CLAUDE.md, AGENTS.md, docs/, .github/, scripts/ (migrations 제외) | src/step*, web/app/, web/components/ |\n"
    "| qa-auditor | Read-only 감사 전용 | Write, Edit 금지 |\n"
    "| ux-auditor | Read-only 감사 전용 | Write, Edit 금지 |\n"
    "| content-director | Read-only 영상 콘텐츠 감사 | Write, Edit 금지 |\n"
    "| performance-analyst | Read-only 분석 전용 | Write, Edit 금지 |\n"
    "| pipeline-debugger | Read-only 파이프라인 분석 | Write, Edit 금지 |\n"
    "| revenue-strategist | Read-only 수익 전략 감사 | Write, Edit 전면 금지 |\n"
    "| legal-counsel | Read-only 법률 검토 · data/legal/ 단독 | Edit 전면 금지 |\n"
    "| cto | 조율 전용 (파일 편집 불가) | Write, Edit 전면 금지 |\n"
    "| ceo | 조율 전용 (파일 편집 불가) | Write, Edit 전면 금지 |\n"
    "| db-architect | scripts/supabase_schema.sql, scripts/migrations/, web/lib/types.ts | src/, web/app/, web/components/ |\n"
    "| code-refactorer | src/ 리팩토링 전용 (worktree) | web/, tests/ 삭제, src/step08/__init__.py |\n"
    "| release-manager | CHANGELOG.md (단독), git tag | src/step*, web/app/, src/step08/__init__.py |\n"
    "| sales-manager | data/sales/ | src/, web/ |\n"
    "| project-manager | data/pm/ | src/, web/ |\n"
    "| marketing-manager | data/marketing/ | src/, web/ |\n"
    "| customer-support | data/cs/ | src/, web/ |\n"
    "| finance-manager | data/finance/ | src/, web/ |\n"
    "| data-analyst | data/bi/ (단독) | src/, web/, data/global/ |\n"
    "| prompt-engineer | src/step*/prompts.py, src/ai_engine/prompts/, data/prompts/ | src/ 로직 코드, web/ |\n"
    "\n"
    "---\n"
    "\n"
    "## 부서간 협업 — TeamCreate 기반 동적 팀\n"
    "\n"
    "### 팀 유형 3종\n"
    "\n"
    "| 유형 | team_name 패턴 | 소환 주체 | 생명주기 |\n"
    "|---|---|---|---|\n"
    "| 상설팀 | `kas-weekly-ops` | ceo (주1회) | 월요일 생성 → 일요일 종료 |\n"
    "| 동적 미션팀 | `client-{id}` / `incident-{날짜}` / `feature-{ticket}` | ceo(비즈니스) · cto(기술) | 미션 시작 → 완료 후 종료 |\n"
    "| 감사팀 | `weekly-audit-{날짜}` | qa-auditor (주1회) | 감사 시작 → 완료 후 종료 |\n"
    "\n"
    "**최대 동시 활성 팀: 5팀** (상설1 + 미션3 + 감사1)\n"
    "\n"
    "### 팀 워크플로우\n"
    "```\n"
    "TeamCreate(team_name=...) -> Agent(team_name, name, subagent_type) x N명 소환\n"
    "-> TaskCreate로 공유 태스크 리스트 작성\n"
    "-> 팀원이 TaskList 보고 자율 claim (pull 방식)\n"
    "-> 팀원 간 SendMessage로 실시간 조율 (idle notification 자동)\n"
    "-> 완료 후 SendMessage(\"*\", shutdown_request) -> TeamDelete\n"
    "-> data/exec/team_lifecycle.json에 기록\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## 미션 프리셋\n"
    "\n"
    "| 미션 유형 | 소환 조합 |\n"
    "|-----------|-----------|\n"
    "| 백엔드 기능/버그 | backend-engineer + qa-auditor |\n"
    "| 프론트엔드 기능 | frontend-engineer + qa-auditor |\n"
    "| UI/디자인 변경 | ui-designer + ux-auditor |\n"
    "| 보안 취약점 수정 | qa-auditor -> backend-engineer/frontend-engineer |\n"
    "| 성능 최적화 | performance-analyst + backend-engineer/frontend-engineer |\n"
    "| DB 스키마 변경 | db-architect + backend-engineer + frontend-engineer |\n"
    "| 파이프라인 장애 | pipeline-debugger + backend-engineer |\n"
    "| 대규모 리팩토링 | code-refactorer + backend-engineer |\n"
    "| 릴리스 배포 | release-manager + backend-engineer |\n"
    "| UX/접근성 감사 | ux-auditor -> frontend-engineer/ui-designer |\n"
    "| 영상 콘텐츠 감사 | content-director -> backend-engineer/ui-designer |\n"
    "| 수익 전략 감사 | revenue-strategist -> backend-engineer + content-director |\n"
    "| 월간 주제 포트폴리오 | revenue-strategist + pipeline-debugger -> backend-engineer |\n"
    "| 수주 프로젝트 | ceo: TeamCreate + sales-manager + project-manager + 제작팀 |\n"
    "| 주간 KAS 운영 | ceo: TeamCreate(kas-weekly-ops) — cto + backend-engineer + content-director 등 |\n"
    "| 법률 검토 | sales-manager -> legal-counsel -> (고위험 시) ceo HITL |\n"
    "| BI 대시보드 | data-analyst (주간 자동) -> ceo/revenue-strategist 보고 |\n"
    "| 프롬프트 최적화 | prompt-engineer + backend-engineer (페어 검토 후 merge) |\n"
    "\n"
    "---\n"
    "\n"
    "## 통신 프로토콜\n"
    "\n"
    "**ceo/cto -> 팀 결성 (TeamCreate)**:\n"
    "```\n"
    "TeamCreate(team_name=\"{유형}-{id}\")\n"
    "Agent(team_name=..., name=\"{역할}\", subagent_type=\"{에이전트명}\")\n"
    "TaskCreate(subject=\"{작업}\", description=\"...\")\n"
    "```\n"
    "\n"
    "**ceo/cto -> 개별 소환 (단발 미션)**:\n"
    "```\n"
    "[미션 ID: YYYY-MM-DD-{유형}]\n"
    "목표: {한 줄}\n"
    "범위: {파일/모듈}\n"
    "제약조건: {금지 사항}\n"
    "완료 기준: {구체적 조건}\n"
    "```\n"
    "\n"
    "**Guardian -> Builder (이슈 전달)**:\n"
    "```\n"
    "[이슈 유형: 보안/품질/UX/수익/법률/데이터]\n"
    "파일: {경로:줄번호}\n"
    "심각도: CRITICAL/HIGH/MEDIUM/LOW\n"
    "설명: {문제와 영향}\n"
    "수정 담당: {에이전트명}\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## Anti-Patterns\n"
    "\n"
    "### 기본 (v5.2 유지)\n"
    "- **backend-engineer가 web/ 수정** — PreToolUse hook 물리적 차단\n"
    "- **qa-auditor가 코드 직접 수정** — disallowedTools로 차단\n"
    "- **Opus 에이전트 동시 2명 초과** — cto + db-architect 동시 활성화 시 cto가 팀 편성 후 먼저 종료\n"
    "- **L3 동시 5명 초과** — 조율 오버헤드\n"
    "- **CHANGELOG.md를 release-manager 외 편집** — 릴리스 이력 충돌\n"
    "- **db-architect 없이 스키마 변경** — RLS/types.ts 동기화 누락\n"
    "\n"
    "### TeamCreate 전용 (v6.0)\n"
    "- **TeamCreate 권한 3명 제한** — ceo·cto·qa-auditor만 보유\n"
    "- **고아 팀 금지** — 미션 종료 시 반드시 shutdown_request -> TeamDelete\n"
    "- **동시 활성 팀 5개 초과 금지** — 상설1 + 미션3 + 감사1 한도\n"
    "- **팀 간 TaskList 교차 claim 금지** — 자기 팀 TaskList만 작업\n"
    "- **부서 SSOT 교차 쓰기 금지** — 팀 내 통신은 자유, data/{부서}/ 쓰기만 자기 부서 제한\n"
    "- **팀 생명주기 감사 로그 필수** — data/exec/team_lifecycle.json 기록\n"
    "\n"
    "### 비즈니스 에이전트 (v6.0)\n"
    "- **HITL 룰 우회 금지** — sales-manager가 단독으로 수주 결정 불가, 반드시 ceo 경유\n"
    "- **비즈니스 에이전트가 src/ 수정** — PreToolUse hook 차단\n"
    "- **신규 에이전트가 기존 에이전트 파일 직접 편집** — 반드시 SendMessage로 위임\n"
    "- **부서장 우회** — 부서 내 의사결정은 부서장 경유\n"
    "\n"
    "### v7.0 신규\n"
    "- **legal-counsel 우회** — sales-manager가 계약서 도착 후 legal-counsel 미경유 금지\n"
    "- **prompt-engineer 단독 merge** — backend-engineer 페어 검토 없이 src/ 프롬프트 수정 금지\n"
    "- **data-analyst Supabase 쓰기** — analytics 뷰/함수 외 DML 실행 금지\n"
    "- **color enum 위반** — 공식 enum(red/blue/green/yellow/purple/orange/pink/cyan) 외 사용 금지\n"
    "- **CLAUDE.md 23명 상세 표 부활 금지** — 단일 출처 원칙: 상세는 AGENTS.md만\n"
    "\n"
    "---\n"
    "\n"
    "## Supabase RLS 경계\n"
    "\n"
    "- **db-architect** (Opus): RLS 정책 1차 설계 + 마이그레이션 + types.ts 동기화\n"
    "- **qa-auditor** (Sonnet): RLS 감사만 (설계 변경 금지)\n"
    "- **data-analyst** (Haiku): analytics 뷰(SELECT 전용) — DML 실행 금지\n"
    "- 이슈 발견 시 SendMessage로 db-architect에 전달\n"
    "- 파괴적 변경(DROP, 타입 축소) 시 백필 스크립트 필수\n"
    "\n"
    "---\n"
    "\n"
    "## Playwright 사용 우선순위\n"
    "\n"
    "1. frontend-engineer — E2E 테스트 작성·실행 (1차 소유)\n"
    "2. ux-auditor — WCAG/반응형 감사 (read-only, Haiku)\n"
    "3. ui-designer — 시각 검증 스크린샷 비교\n"
    "4. content-director — /runs 썸네일 검토\n"
    "\n"
    "충돌 시 frontend-engineer 우선, 감사 에이전트는 read-only 모드 유지.\n"
    "\n"
    "---\n"
    "\n"
    "## 진단 에이전트 경계 (4축)\n"
    "\n"
    "- **pipeline-debugger** (Sonnet): Step 실패 \"원인\" (로그·manifest·quota·지식 품질)\n"
    "- **performance-analyst** (Haiku): 성공 런의 \"최적화\" (N+1·메모리·번들·time.sleep)\n"
    "- **revenue-strategist** (Sonnet): 주제 선별 \"수익성\" (scorer·portfolio·winning pattern)\n"
    "- **data-analyst** (Haiku): BI \"현황\" (채널 코호트·펀널·A/B 결과 — 정기 보고)\n"
    "\n"
    "동일 이슈에 둘 이상 소환 금지 — cto가 1개 선택.\n"
    "\n"
    "---\n"
    "\n"
    "## teammate 모드 동작\n"
    "\n"
    "- 모든 23개 agent는 teammate 모드(`CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1`)로 운영.\n"
    "- `skills`·`mcpServers`는 teammate 모드에서 무시됨 — agent frontmatter에 선언하지 않음.\n"
    "- context7·playwright·figma MCP는 `.claude/settings.local.json`에서 전역 로드.\n"
    "\n"
    "| 에이전트 | 권장 skill (팀원 단독 실행 시) |\n"
    "|---|---|\n"
    "| ceo | superpowers:brainstorming, superpowers:writing-plans |\n"
    "| cto | superpowers:brainstorming, superpowers:writing-plans |\n"
    "| backend-engineer | superpowers:test-driven-development, superpowers:systematic-debugging |\n"
    "| frontend-engineer | superpowers:test-driven-development, frontend-design:frontend-design |\n"
    "| ui-designer | frontend-design:frontend-design, ui-ux-pro-max:ui-ux-pro-max |\n"
    "| qa-auditor | superpowers:requesting-code-review |\n"
    "| devops-engineer | claude-md-management:revise-claude-md |\n"
    "\n"
    "---\n"
    "\n"
    "## 실전 협업 시나리오\n"
    "\n"
    "### 시나리오 1: 파이프라인 장애 (Step08 FFmpeg 실패)\n"
    "```\n"
    "/mission \"Step08 FFmpeg 에러 조사\"\n"
    "-> cto: TeamCreate(\"incident-{날짜}-step08\")\n"
    "  1) pipeline-debugger: 로그·manifest·쿼터 분석 (read-only)\n"
    "  2) backend-engineer: 수정 구현 (src/step08/ffmpeg_composer.py)\n"
    "-> pipeline-debugger -> SendMessage -> backend-engineer에 근본 원인 전달\n"
    "-> 수정 -> pytest -> TeamDelete\n"
    "```\n"
    "\n"
    "### 시나리오 2: 외주 클라이언트 프로젝트 (legal 포함)\n"
    "```\n"
    "sales-manager -> 리드 기록 -> 제안서 작성\n"
    "-> legal-counsel: 계약서 검토 -> (고위험 없음) -> ceo 보고\n"
    "-> ceo HITL 게이트 (>=100만원) -> 사용자 승인\n"
    "-> ceo: TeamCreate(\"client-{id}\")\n"
    "  + project-manager, content-director, backend-engineer, ui-designer,\n"
    "    qa-auditor, customer-support, finance-manager\n"
    "-> 공유 TaskList (스펙->렌더->QA->전달->청구)\n"
    "-> 팀원 자율 claim -> 완료 -> TeamDelete\n"
    "```\n"
    "\n"
    "### 시나리오 3: Supabase 스키마 변경\n"
    "```\n"
    "/mission \"trend_topics에 is_approved_by 컬럼 추가\"\n"
    "-> cto spawn:\n"
    "  1) db-architect: SQL 마이그레이션 + RLS (Opus, worktree)\n"
    "  2) backend-engineer: src/agents/ui_ux/ 동기화 로직 (worktree)\n"
    "  3) frontend-engineer: web/lib/types.ts 재생성 (worktree)\n"
    "-> db-architect가 나머지 2명에 API 변경 알림 -> 병렬 구현 -> 통합\n"
    "```\n"
    "\n"
    "### 시나리오 4: 월간 BI 보고 (v7.0 신규)\n"
    "```\n"
    "data-analyst (주간 자동 or cron)\n"
    "-> scripts/generate_bi_dashboard.py 실행\n"
    "-> data/bi/weekly_dashboard.json 생성\n"
    "-> SendMessage(revenue-strategist) — winning pattern 대조\n"
    "-> SendMessage(ceo) — 월간 경영 보고 입력\n"
    "```\n"
    "\n"
    "---\n"
    "\n"
    "## 자주 쓰는 커맨드\n"
    "\n"
    "```bash\n"
    "claude agents                                    # 23개 에이전트 목록 확인\n"
    "pytest tests/ -x -q --ignore=tests/test_step08_integration.py\n"
    "ruff check src/ --fix --select=E,W,F,I\n"
    "cd web && npm run build\n"
    "python scripts/generate_bi_dashboard.py         # BI 대시보드 생성\n"
    "python scripts/generate_monthly_report.py       # 월간 경영 리포트\n"
    "python scripts/detect_orphan_teams.py           # 고아 팀 탐지\n"
    "```\n"
    "\n"
    "## Slash Commands (`.claude/commands/`)\n"
    "\n"
    "| 커맨드 | 설명 |\n"
    "|---|---|\n"
    "| `/mission [설명]` | cto 소환 — HITL/실패 자동 감지 + 팀 편성 |\n"
    "| `/audit [범위]` | qa-auditor + performance-analyst 병렬 감사 |\n"
    "| `/release [버전]` | release-manager 소환 — CHANGELOG + tag + PR |\n"
    "| `/kpi [채널]` | AnalyticsLearningAgent KPI 수집 및 Phase 분석 |\n"
    "| `/debug-pipeline [step]` | pipeline-debugger 소환 — Step 실패 분석 |\n"
    "| `/verify [범위]` | 완료 전 검증 — pytest + ruff + build 통과 확인 |\n"
    "| `/revenue-audit` | revenue-strategist 소환 — scorer/portfolio/winning pattern 감사 |\n"
)

AGENTS_MD.write_text(CONTENT, encoding="utf-8")
lines = len(CONTENT.splitlines())
print(f"[OK] AGENTS.md v7.0 작성 완료: {lines}줄")

# 검증
text = AGENTS_MD.read_text(encoding="utf-8")
assert "Loomix" in text, "Loomix 브랜딩 누락"
assert "23개" in text, "에이전트 수 누락"
assert "Data Intelligence" in text, "신규 부서 누락"
assert "legal-counsel" in text, "legal-counsel 누락"
assert "data-analyst" in text, "data-analyst 누락"
assert "prompt-engineer" in text, "prompt-engineer 누락"
assert "v7.0 신규" in text, "v7.0 Anti-Pattern 누락"
print("[OK] 필수 키워드 7개 검증 통과")
