"""UI/UX Agent — 대시보드 스키마 변경 감지 및 TypeScript 타입 자동 동기화."""
import re
from pathlib import Path
from typing import Any, Optional
from loguru import logger
from src.agents.base_agent import BaseAgent
from src.agents.ui_ux.schema_watcher import has_schema_changed, save_schema_hash
from src.agents.ui_ux.type_syncer import extract_columns_from_sql, generate_ts_interface


class UiUxAgent(BaseAgent):
    """스키마 변경을 감지하고 web/lib/types.ts를 자동 동기화한다."""

    def __init__(self, root: Optional[Path] = None):
        super().__init__("UiUx")
        # root=None 이면 BaseAgent 기본값(프로젝트 루트)을 사용한다
        if root is not None:
            self.root = root

    def run(self) -> dict[str, Any]:
        """스키마 변경 여부를 확인하고 변경 시 타입 동기화를 수행한다.

        Returns:
            {
                "schema_changed": bool,
                "synced_tables": list,
            }
        """
        self._log_start()

        sql_path = self.root / "scripts" / "supabase_schema.sql"
        types_path = self.root / "web" / "lib" / "types.ts"
        state_path = self.root / "data" / "global" / ".ui_schema_state.json"
        state_path.parent.mkdir(parents=True, exist_ok=True)

        if not sql_path.exists():
            logger.warning(f"[{self.name}] {sql_path} 없음 — 스킵")
            return {"schema_changed": False, "synced_tables": []}

        changed = has_schema_changed(sql_path, state_path)
        synced_tables: list = []

        if changed:
            logger.info(f"[{self.name}] 스키마 변경 감지 — 타입 동기화 시작")
            sql_content = sql_path.read_text(encoding="utf-8")
            tables = re.findall(
                r"CREATE TABLE(?:\s+IF NOT EXISTS)?\s+(\w+)", sql_content, re.IGNORECASE
            )

            new_interfaces = []
            for table in tables:
                columns = extract_columns_from_sql(sql_content, table)
                if columns:
                    new_interfaces.append(generate_ts_interface(table, columns))
                    synced_tables.append(table)

            if new_interfaces:
                if types_path.exists():
                    existing = types_path.read_text(encoding="utf-8")
                    marker = "// AUTO-GENERATED by UiUxAgent — DO NOT EDIT BELOW"
                    base = existing.split(marker)[0].rstrip()
                    updated = base + f"\n\n{marker}\n" + "\n\n".join(new_interfaces) + "\n"
                    types_path.write_text(updated, encoding="utf-8")
                    logger.info(f"[{self.name}] types.ts 업데이트: {synced_tables}")
                else:
                    logger.warning(f"[{self.name}] {types_path} 없음 — 해시 저장 건너뜀")
                    return {"schema_changed": True, "synced_tables": []}

            save_schema_hash(sql_path, state_path)

        report: dict[str, Any] = {"schema_changed": changed, "synced_tables": synced_tables}
        self._log_done(report)
        return report
